[project]
name = "douc-labs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bernie Camejo", email = "bernie.camejo@icloud.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard-no-fastapi-cli]>=0.141.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "httpx>=0.28.1",
]

[project.scripts]
douc-labs = "douc_labs:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"